### ISSUE TITLE
RejectedExecutionException when building with IntelliJ

### ISSUE THREAD

**Issue by enekonieto** [benkuly/matrix-spring-boot-sdk#8]
First of all, it seems this is first issue reported (apart of yours), so... Thank you for sharing your work!! This lib is just what I was searching for, it makes me very happy being able to interact with my homeserver so easily using Spring Boot, instead of using C, Node.js or another language. Spring Boot is an amazing framewok, and Kotlin is delicious :)

Now, the bug report:
I am used to launch Spring Boot apps with `./gradlew bootrun` while developing an building project from IntelliJ (Build -> Build project). This way the app is built and automatically relaunched very quickly.

Since I introduced this lib I get a RejectedExecutionException when rebuilding, and I have to kill `gradlew` and relaunch.

Full stack:
```
2021-03-26 00:30:18.741 ERROR 29090 --- [atcher-worker-1] n.f.m.r.a.sync.SyncApiClient$Companion   : error while sync to server: event executor terminated; nested exception is java.util.concurrent.RejectedExecutionException: event executor terminated
2021-03-26 00:30:19.482 ERROR 29090 --- [atcher-worker-1] n.f.m.r.a.sync.SyncApiClient$Companion   : error while sync to server: executor not accepting a task; nested exception is java.lang.IllegalStateException: executor not accepting a task
2021-03-26 00:30:21.486  WARN 29090 --- [atcher-worker-1] io.netty.channel.AbstractChannel         : Force-closing a channel whose registration task was not accepted by an event loop: [id: 0xa0cb78f4]

java.util.concurrent.RejectedExecutionException: event executor terminated
        at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:926) ~[netty-common-4.1.55.Final.jar:4.1.55.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:353) ~[netty-common-4.1.55.Final.jar:4.1.55.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:346) ~[netty-common-4.1.55.Final.jar:4.1.55.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:828) ~[netty-common-4.1.55.Final.jar:4.1.55.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:818) ~[netty-common-4.1.55.Final.jar:4.1.55.Final]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:471) ~[netty-transport-4.1.55.Final.jar:4.1.55.Final]
        at reactor.netty.transport.TransportConnector.doInitAndRegister(TransportConnector.java:187) ~[reactor-netty-core-1.0.2.jar:1.0.2]
        at reactor.netty.transport.TransportConnector.connect(TransportConnector.java:102) ~[reactor-netty-core-1.0.2.jar:1.0.2]
        at reactor.netty.resources.DefaultPooledConnectionProvider$PooledConnectionAllocator.lambda$connectChannel$0(DefaultPooledConnectionProvider.java:524) ~[reactor-netty-core-1.0.2.jar:1.0.2]
        at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:57) ~[reactor-core-3.4.1.jar:3.4.1]
        at reactor.core.publisher.Mono.subscribe(Mono.java:4046) ~[reactor-core-3.4.1.jar:3.4.1]
        at reactor.core.publisher.Mono.subscribeWith(Mono.java:4161) ~[reactor-core-3.4.1.jar:3.4.1]
        at reactor.core.publisher.Mono.subscribe(Mono.java:4017) ~[reactor-core-3.4.1.jar:3.4.1]
        at reactor.core.publisher.Mono.subscribe(Mono.java:3953) ~[reactor-core-3.4.1.jar:3.4.1]
        at reactor.core.publisher.Mono.subscribe(Mono.java:3925) ~[reactor-core-3.4.1.jar:3.4.1]
        at reactor.netty.internal.shaded.reactor.pool.SimpleDequePool.drainLoop(SimpleDequePool.java:318) ~[reactor-netty-core-1.0.2.jar:1.0.2]
        at reactor.netty.internal.shaded.reactor.pool.SimpleDequePool.drain(SimpleDequePool.java:261) ~[reactor-netty-core-1.0.2.jar:1.0.2]
        at reactor.netty.internal.shaded.reactor.pool.SimpleDequePool.doAcquire(SimpleDequePool.java:256) ~[reactor-netty-core-1.0.2.jar:1.0.2]
        at reactor.netty.internal.shaded.reactor.pool.AbstractPool$Borrower.request(AbstractPool.java:382) ~[reactor-netty-core-1.0.2.jar:1.0.2]
        at reactor.netty.resources.DefaultPooledConnectionProvider$DisposableAcquire.onSubscribe(DefaultPooledConnectionProvider.java:206) ~[reactor-netty-core-1.0.2.jar:1.0.2]
        at reactor.netty.internal.shaded.reactor.pool.SimpleDequePool$QueueBorrowerMono.subscribe(SimpleDequePool.java:578) ~[reactor-netty-core-1.0.2.jar:1.0.2]
        at reactor.netty.resources.PooledConnectionProvider.lambda$acquire$1(PooledConnectionProvider.java:120) ~[reactor-netty-core-1.0.2.jar:1.0.2]
        at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:57) ~[reactor-core-3.4.1.jar:3.4.1]
        at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect.lambda$subscribe$0(HttpClientConnect.java:266) ~[reactor-netty-http-1.0.2.jar:1.0.2]
        at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:57) ~[reactor-core-3.4.1.jar:3.4.1]
        at reactor.core.publisher.FluxRetryWhen.subscribe(FluxRetryWhen.java:76) ~[reactor-core-3.4.1.jar:3.4.1]
        at reactor.core.publisher.MonoRetryWhen.subscribeOrReturn(MonoRetryWhen.java:46) ~[reactor-core-3.4.1.jar:3.4.1]
        at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57) ~[reactor-core-3.4.1.jar:3.4.1]
        at reactor.netty.http.client.HttpClientConnect$MonoHttpConnect.subscribe(HttpClientConnect.java:269) ~[reactor-netty-http-1.0.2.jar:1.0.2]
        at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[reactor-core-3.4.1.jar:3.4.1]
        at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[reactor-core-3.4.1.jar:3.4.1]
        at reactor.core.publisher.Mono.subscribe(Mono.java:4046) ~[reactor-core-3.4.1.jar:3.4.1]
        at kotlinx.coroutines.reactive.AwaitKt.awaitOne(Await.kt:137) ~[kotlinx-coroutines-reactive-1.4.2.jar:na]
        at kotlinx.coroutines.reactive.AwaitKt.awaitOne$default(Await.kt:135) ~[kotlinx-coroutines-reactive-1.4.2.jar:na]
        at kotlinx.coroutines.reactive.AwaitKt.awaitSingle(Await.kt:81) ~[kotlinx-coroutines-reactive-1.4.2.jar:na]
        at net.folivo.matrix.restclient.api.sync.SyncApiClient.syncOnce(SyncApiClient.kt:91) ~[matrix-spring-boot-rest-client-0.4.5.jar:na]
        at net.folivo.matrix.restclient.api.sync.SyncApiClient$syncLoop$1$response$1.invokeSuspend(SyncApiClient.kt:66) ~[matrix-spring-boot-rest-client-0.4.5.jar:na]
        at net.folivo.matrix.restclient.api.sync.SyncApiClient$syncLoop$1$response$1.invoke(SyncApiClient.kt) ~[matrix-spring-boot-rest-client-0.4.5.jar:na]
        at com.github.michaelbull.retry.RetryKt$retry$5.invokeSuspend(Retry.kt:52) ~[kotlin-retry-1.0.6.jar:na]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[kotlin-stdlib-1.4.21.jar:1.4.21-release-351 (1.4.21)]
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[kotlinx-coroutines-core-jvm-1.4.2.jar:na]
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571) ~[kotlinx-coroutines-core-jvm-1.4.2.jar:na]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) ~[kotlinx-coroutines-core-jvm-1.4.2.jar:na]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678) ~[kotlinx-coroutines-core-jvm-1.4.2.jar:na]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665) ~[kotlinx-coroutines-core-jvm-1.4.2.jar:na]
```

**Comment by benkuly** [comment]
Thanks :slightly_smiling_face: It's awesome, that someone uses this sdk!

I will take a look into it in the next few days. I think the problem is, that the event-stream, which is produced by the matrix-server-sync-loop isn't closed when the application get's shut down.

I'm also working on a successor of this sdk, which uses [trixnity](https://github.com/benkuly/trixnity) as base. Trixnity is written in pure multiplatform Kotlin and therefore can also be used for native and JS applications. When trixnity and the successor of matrix-spring-boot-sdk is working, I'm ready to implement new features for trixnity (multimedia-support, reaction-support, complete client-state-sync, encryption, ...).

**Comment by benkuly** [comment]
Should be fixed with version 0.4.6 :)

**Comment by enekonieto** [comment]
Thanks! Could you post in Maven repository?

**Comment by benkuly** [comment]
sorry, forgot that. Is published :)

**Comment by enekonieto** [comment]
It works, thank you!!
